# classes with respective sample sentences
opening_lexicons = {'standard_greeting': ['good time to talk', 'good morning', 'good afternoon', 'good evening', 'calling from income', 'hello i am looking for mister', 'may i speak with', 'calling for the number', 'this is agent from income ntuc'],
                    'purpose_of_call': ['the purpose of my call is to inform you', 'as a valued customer of income', 'we have designed this plan called', 'this plan is for exclusive customers like yourself', 'we formulated a special fiftieth anniversary insurance bundle called the i fifty', 'we have this anniversary plan for the family'],
                    'ask_for_permission': ['how may i address you', 'may i call you', 'is it a good time to talk to you', 'are you convenient to talk', 'are you free to talk', 'do you have one or two minutes to talk', 'can i check with you if it is a good time to speak for a while']}

closing_lexicons = {'follow_up': ['can i contact you later in the afternoon', 'i will call you at four or five', 'i will call you back on monday', 'you prefer morning or afternoon', 'i will do a follow up call next week', 'i will drop you an email', 'i will call you at another time', 'you can give me a call at this number', 'you can give us a call back'],
                    'data_enrichment': ['what is your email address', 'am i pronuncing your name correctly', 'do you have any other questions', 'can i have your updated email address', 'can i send you a survey via sms after the call', 'can you provide your updated phone number please', 'may i confirm is the current email address'],
                   'standard_closing': ['thank you so much for your time', 'have a great time', 'have a nice day', 'have a good day', 'okay then bye thanks', 'thank you bye bye', 'bye bye', 'wish you a good day', 'thank you for insuring with income', 'please do not hesitate to contact me', 'no problem thank you', 'anything else i can assist you with', 'thank you for your time', 'xie xie']}

