# This python helper file should be after sentiment score generation
# First create dictionary with category, sentence, sentiment
# Then can visualize through pandas dataframe
import numpy as np
import pandas as pd
import sys
sys.path.insert(0, "/Users/leon/Income/python files/Telesales-QA-Framework")
from helper.lexicons import *
# take the list generated by nlp_sentiment, and create dictionary using category name as key name
# each element in result_ls is like [category, sentence, sentiment]
def result_reformat(result_ls, lexicon_dic):    
    result_dic = {} # initialize result dictionary
    for i, result in enumerate(result_ls):
        category = result[0]
        sentence = result[1]
        sentiment = result[2]

        if category in result_dic: # check if the category is in our newly created result_dic
            result_dic[category].append([sentence, sentiment])
        else:
            result_dic[category] = [[sentence, sentiment]]
    return result_dic

def assign_score(result_dic, lexicon_dic):
    temp_score_dic = {}
    for category, info in result_dic.items():
        sentiments = map(lambda x: x[1], info)
        passed = True
        for sentiment in sentiments:
            if sentiment == 'negative':
                passed = False
        temp_score_dic[category] = passed
    final_score_dic = {}
    for key in lexicon_dic.keys():
        if key in temp_score_dic:
            if temp_score_dic[key] == True:
                final_score_dic[key] = True
            else:
                final_score_dic[key] = False
        else:
            final_score_dic[key] = False
    return final_score_dic
   
